language: node_js
node_js:
 - '0.10'
notifications:
  email: false
  irc:
    channels:
    - 'chat.freenode.net#hoodie'
    skip_join: true
before_install:
- npm install -g grunt-cli
- git clone git://github.com/n1k0/casperjs.git ~/casperjs
- cd ~/casperjs
- git checkout tags/1.0.2
- export PATH=$PATH:`pwd`/bin
- cd -
- npm install -g hoodie-cli
before_script:
- phantomjs --version
- casperjs --version
- hoodie new myapp
- cd myapp
- hoodie start &
- sleep 10
- cd -
