language: node_js
node_js:
- '0.10'
services:
- couchdb
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#hoodie
    skip_join: true
  slack:
    secure: ZMz9TDAQMC2gDIngNN+p69ftHhFeQ48wQ36j8XkPzPRO1ErMLC1dM6EPAzcm8TL2cPtq4rXLz0/5HjQe91RZwqXnJ1kpHOuNBf7VNJPq81DzITdfUtrd4Bv6lI9bIfnlkJu8OrVZp+z/w50jDx4WApATNeTwiBEKr4qWHU/DHLQ=
before_install:
- npm install -g grunt-cli
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
env:
  global:
  - secure: Z8QEPjDeekJRdiAEQA+ARDRRrS8egpzS1WFu68+KQWcDuFg1FeVGYO1A2HyPHggfA/8L+NUfAv0YQi/VvJ6C/zTlO5BhqurumVOtV4U08s3mLmbRSBwkE9kPXLHWJrIoMGdTG93I/SrzL6h4qUTRNSjkfz6F2VcfpcwH9TuR84Q=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  api_key:
    secure: jzyuKi/FCKviFFgYbQo3dt90e6ByLVzniKCyeu86Q+yOvYreON5LJ7tYtSZOUJqqQ5XRQgV3PKRGT7ldJyEY00xWw600vtPIBxMVJMezwLg+W0ikMHgVNriJbMjTI0P1lTnR1deeErYWrcpU3/SIVKA467SFx125M7rs2tfuH0M=
  on:
    all_branches: true
    tags: true
sudo: false
cache:
  directories:
  - node_modules
