language: node_js
node_js:
- '0.10'
services:
- couchdb
notifications:
  email: false
  irc:
    channels:
    - 'chat.freenode.net#hoodie'
    skip_join: true
before_install:
- npm install -g grunt-cli
