/*global casper:false */
var hosts = require('../../hosts.json');

casper.test.begin('SignIn to Admin Dashboard', function(test) {
  casper.start(hosts.admin);

  // This tests fails because the login form does not become visible.
  // There are no JS errors and the CSS is fine. My guess is that the
  // HTML generated by the dashboard app is invalid. If I comment out
  // the current <body> tag with its <script> tags and replace it with
  // the static HTML from Chrome's inspector, it works all fine. Well
  // possible that Chrome auto-fixed the HTML.
  //
  // Next step would be to look trough the templates of the admin dashboard
  // app and look for tags that don't get closed.

  casper.waitUntilVisible('[data-component="login"]');

  casper.thenClick('input[name=password]');
  casper.then(function() {
    this.sendKeys('input[name=password]', '12345');
  });
  casper.thenClick('button[type=submit]');

  casper.waitUntilVisible('[data-component="content"]');
  casper.then(function() {
    this.assertVisible('[data-component="content"]');
  });
});
